INSERT INTO manufacturer (name, country_id)
VALUES 
('Établissement de Constructions et de Réparation Navale (ECRN)', 3),
('Bersa', 4),
('Fabricaciones Militares', 4),
('Fábrica 4 de Aviones', 4),
('Río Santiago Shipyard', 4),
('ASC', 5),
('Austal', 5),
('BSC Marine Group', 5),
('DMS Maritime', 5),
('Forgacs Marine & Defence', 5),
('Metal Storm', 5),
('NIOA', 5),
('NQEA', 5),
('Diamond Aircraft Industries', 6),
('Glock Ges.m.b.H.', 6),
('Rößler (Roessler Waffen GmbH)', 6),
('Steyr Arms', 6),
('Ministry of Defence Industry of Azerbaijan', 7),
('Bangladesh Ordnance Factories', 8),
('Bangladesh Machine Tools Factory', 8),
('Dockyard and Engineering Works', 8),
('Khulna Shipyard', 8),
('Chittagong Dry Dock', 8),
('Forges de Zeebrugge', 10),
('Herstal Group', 10),
('John Cockerill', 10),
('Belarusian Optical Mechanical Association', 9),
('Fabrica Boliviana de Munición (FBM)', 11),
('Arsenal de Marinha do Rio de Janeiro', 12),
('Avibras', 12),
('Companhia Brasileira de Cartuchos', 12),
('Embraer', 12),
('EMGEPRON', 12),
('Indústria Naval do Ceará', 12),
('IMBEL', 12),
('SIATT', 12),
('Taurus', 12),
('Arsenal Corporation', 13),
('TEREM', 13),
('VMZ Sopot', 13),
('ABCO Industries', 14),
('A. F. Theriault Shipyard', 14),
('Bombardier Inc.', 14),
('Cadex Defence', 14),
('Cascade Aerospace', 14),
('Davie Shipbuilding', 14),
('INKAS', 14),
('Irving Shipbuilding', 14),
('Magellan Aerospace Corporation', 14),
('MetalCraft Marine', 14),
('Ontario Drive and Gear Ltd. (ARGO)', 14),
('Seaspan Marine Corporation', 14),
('Viking Air', 14),
('ASMAR', 15),
('ENAER', 15),
('FAMAE', 15),
('Aviation Industry Corporation of China (AVIC)', 16),
('China Aerospace Science and Industry Corporation (CASIC)', 16),
('China Aerospace Science and Technology Corporation', 16),
('China Electronics Technology Group', 16),
('Norinco (China North Industries Group)', 16),
('China South Industries Group', 16),
('China State Shipbuilding Corporation', 16),
('Poly Technologies', 16),
('Weichai Group', 16),
('COTECMAR', 71),
('Corporación de la Industria Aeronáutica 71na S.A. (CIAC)', 71),
('Indumil', 71),
('ISBI ARMORing Inc. (ISBI)', 71),
('Brodosplit d.d.', 18),
('Đuro Đaković', 18),
('HS Produkt', 18),
('Marina Punat', 18),
('Union de Industrias Militares', 19),
('Aero Vodochody', 20),
('Colt CZ Group', 20),
('Czechoslovak Group', 20),
('Zlin Aviation', 20),
('Česká zbrojovka (CZ)', 20),
('Tatra (military vehicles)', 20),
('Zbrojovka Brno', 20),
('Faaborg Shipyard', 21),
('Karstensens Skibsværft A/S', 21),
('Terma A/S', 21),
('Dirección de la Industria Aeronáutica Ecuador', 22),
('Alexandria Shipyard', 23),
('Arab Organization for Industrialization', 23),
('Baltic Workboats', 24),
('Metals and Engineering Corporation', 25),
('Marine Alutech (Watercat)', 26),
('Patria', 26),
('Pirkan ASE', 26),
('Rauma Marine Constructions', 26),
('SAKO', 26),
('Uki Workboat', 26),
('Centigon Security Group', 27),
('Chapuis Armes', 27),
('Constructions industrielles de la Méditerranée', 27),
('Daher', 27),
('Dassault Group', 27),
('KNDS 27', 27),
('MBDA', 27),
('Naval Group', 27),
('PGM Precision', 27),
('PIRIOU', 27),
('Renault Trucks', 27),
('Safran S.A.', 27),
('Socarenam', 27),
('Thales Group', 27),
('Verney-Carron', 27),
('Abeking & Rasmussen', 29),
('Blaser', 29),
('Carl Walther GmbH', 29),
('Diehl Aerospace', 29),
('Diehl Defence', 29),
('Fassmer', 29),
('Flensburger Fahrzeugbau', 29),
('Lürssen', 29),
('Hartmann & Weiss', 29),
('Heckler & Koch', 29),
('Heym AG', 29),
('Hensoldt AG', 29),
('Howaldtswerke-Deutsche Werft', 29),
('Krieghoff', 29),
('J. G. Anschütz', 29),
('KNDS Deutschland', 29),
('Mauser Jagdwaffen GmbH', 29),
('PTW KORTH Technologies GmbH (Korth)', 29),
('Rheinmetall AG', 29),
('ThyssenKrupp', 29),
('Ziegenhahn & Sohn', 29),
('STC Delta', 28),
('BSK Defense', 30),
('Hellenic Aerospace Industry', 30),
('Hellenic Defence Systems (EAS)', 30),
('Hellenic Vehicle Industry', 30),
('Motomarine S.A.', 30),
('Ordtech Military Industries (OMI)', 30),
('Advanced Weapons and Equipment 31', 31),
('Ashok Leyland Defence Systems', 31),
('Armoured Vehicles Nigam', 31),
('BEML', 31),
('Bharat Dynamics', 31),
('Bharat Electronics', 31),
('BrahMos Aerospace', 31),
('Cochin Shipyard', 31),
('Garden Reach Shipbuilders & Engineers', 31),
('Gliders 31', 31),
('Goa Shipyard', 31),
('Hindustan Aeronautics', 31),
('Hindustan Shipyard', 31),
('India Optel', 31),
('Kalyani Group', 31),
('Larsen & Toubro', 31),
('Mahindra Group', 31),
('Mazagon Dock Shipbuilders', 31),
('Mishra Dhatu Nigam', 31),
('MKU', 31),
('Munitions 31', 31),
('Samtel Avionics', 31),
('SSS Defence', 31),
('Tata Advanced Systems', 31),
('Troop Comforts', 31),
('Yantra India', 31),
('Indonesian Aerospace', 32),
('North Sea Boats (PT Lundin Industry Invest)', 32),
('PT PAL 32', 32),
('PT Palindo Marine', 32),
('PT Pindad', 32),
('Aerospace Industries Organization (AIO)', 33),
('Defense Industries Organization (DIO)', 33),
('Iran Aviation Industries Organization (IAIO)', 33),
('Iran Electronics Industries (IEI)', 33),
('Iran Marine Industrial Company (SADRA)', 33),
('Iran Shipbuilding & Offshore Industries Complex Co (ISOICO)', 33),
('Marine Industries Organization (MIO)', 33),
('Automotive Industries', 34),
('BUL Armory', 34),
('Carmor', 34),
('Elbit Systems', 34),
('Emtan Karmiel', 34),
('Israel Aerospace Industries', 34),
('Israel Shipyards', 34),
('Israel Weapon Industries', 34),
('mPrest Systems', 34),
('Plasan', 34),
('RADA Electronic Industries', 34),
('Rafael Advanced Defense Systems', 34),
('UVision Air', 34),
('Zibar', 34),
('Armi Jager (Nuova Jager)', 35),
('Perazzi', 35),
('Baglietto Navy', 35),
('BCM Europearms s.a.s.', 35),
('Benelli Armi', 35),
('Beretta', 35),
('Breda Meccanica Bresciana (Breda)', 35),
('Chiappa Firearms', 35),
('Tecnam', 35),
('DRASS', 35),
('FAMARS', 35),
('FB Design', 35),
('Fincantieri', 35),
('Fiocchi Munizioni', 35),
('Franchi', 35),
('Intermarine', 35),
('Iveco', 35),
('Leonardo', 35),
('Piaggio Aerospace', 35),
('Vittoria Shipyard', 35),
('Vulcanair', 35),
('Asahi-Seiki Manufacturing', 36),
('Daikin', 36),
('Hitachi', 36),
('Hongawara Ship Yard', 36),
('Howa', 36),
('IHI Corporation', 36),
('Ishikawa Seisakusho', 36),
('Japan Steel Works', 36),
('JFE Holdings', 36),
('Kawasaki Heavy Industries', 36),
('Komatasu', 36),
('MinebeaMitsumi', 36),
('Mitsubishi Group', 36),
('Mitsui Engineering & Shipbuilding', 36),
('Sasebo Heavy Industries', 36),
('Setouchi Craft', 36),
('ShinMaywa', 36),
('Subaru Corporation', 36),
('Sumidagawa Shipyard (SSY)', 36),
('Sumitomo Heavy Industries', 36),
('Toshiba Corporation', 36),
('Yamaha Motor Company', 36),
('Jordan Design and Development Bureau', 37),
('Kazakhstan Engineering', 38),
('Kenya Ordnance Factories Corporation', 39),
('Dartz', 40),
('JSC Riga Shipyard', 40),
('JSC LiTak-Tak', 4),
('Beretta Holding (Multinational)', 42),
('Boustead Heavy Industries Corporation Berhad (BHIC)', 43),
('DefTech', 43),
('Destini Berhad', 43),
('Aguila Ammunition (TECNOS)', 44),
('Productos Mendoza', 44),
('Myanmar Directorate of Defence Industries', 45),
('Airbus (Multinational)', 46),
('Damen Group', 46),
('Defenture', 46),
('KMW+Nexter Defense Systems (Multinational)', 46),
('Defence Industries Corporation of Nigeria', 47),
('MZT (Makedonska Zeleznicka Tehnika)', 48),
('Kongsberg Gruppen', 49),
('Nammo AS', 49),
('Umoe Mandal', 49),
('Global Industrial Defence Solutions (GIDS)', 50),
('Heavy Industries Taxila (HIT)', 50),
('Integrated Dynamics', 50),
('Karachi Shipyard', 50),
('National Engineering and Scientific Commission (NESCOM)', 50),
('National Radio & Telecommunication Corporation (NRTC)', 50),
('Pakistan Aeronautical Complex (PAC)', 50),
('Pakistan Ordnance Factories (POF)', 50),
('Servicios Industriales de la Marina S.A. (SIMA Peru S.A.)', 51),
('Armscor', 52),
('Government Arsenal', 52),
('Ferfrans', 52),
('Philippine Aerospace Development Corporation', 52),
('United Defense Manufacturing Corporation', 52),
('AMZ-Kutno', 53),
('Polish Armaments Group (PGZ)', 53),
('Polish Defence Holding (PHO)', 53),
('Tekever Group (TEKEVER)', 54),
('West Sea', 54),
('Aerostar', 55),
('Avioane Craiova', 55),
('Industria Aeronautică Română', 55),
('ROMARM', 55),
('Bucharest Mechanical Factory', 55),
('Naval Shipyard  Damen Galați', 55),
('Almaz-Antey', 56),
('Almaz-Antey (air defense systems)', 56),
('Aviaconversiya', 56),
('Barnaul Cartridge Plant', 56),
('Bryansk Automobile Plant', 56),
('Concern Morinformsystem-Agat', 56),
('Concern Radio-Electronic Technologies (KRET)', 56),
('Energia', 56),
('Financial and Industrial Group High-speed ships', 56),
('GAZ Group', 56),
('High Precision Systems', 56),
('Kalashnikov Concern (formerly Izhmash)', 56),
('Kamaz', 56),
('Klimovsk Specialized Ammunition Plant', 56),
('Lavochkin', 56),
('Lobaev Arms', 56),
('Makeyev Rocket Design Bureau', 56),
('Military Industrial Company', 56),
('Motovilikha Plants', 56),
('Rostec (umbrella for many Soviet-era enterprises)', 56),
('ORSIS', 56),
('Open JSC Pella (Pella)', 56),
('Progress Rocket Space Centre', 56),
('Roscosmos', 56),
('RTI Systems', 56),
('Ruselectronics', 56),
('Russia56n Helicopters', 56),
('Shvabe Holding', 56),
('Sozvezdie', 56),
('Tactical Missiles Corporation', 56),
('Tecmash', 56),
('United Aircraft Corporation', 56),
('United Shipbuilding Corporation', 56),
('UralAZ', 56),
('Uralvagonzavod', 56),
('High-Precision Systems', 56),
('Vega Radio Engineering Corporation', 56),
('Zelenodolsk Shipyard', 56),
('Saudi Arabian Military Industries', 57),
('Yugoimport SDPR', 58),
('Krušik', 58),
('PPT Namenska', 58),
('Prvi Partizan', 58),
('Sloboda Čačak', 58),
('EDePro', 58),
('Zastava Arms', 58),
('ST Engineering', 59),
('Grand Power s.r.o.', 60),
('Konstrukta-Defence', 60),
('Ravne Systems Armas', 61),
('ZVS Holding', 61),
('DCD Group', 62),
('Denel', 62),
('Milkor (Pty) Ltd', 62),
('Paramount Group', 62),
('Rippel Effect (Pty) Ltd.', 62),
('Truvelo Armoury', 62),
('Doosan Group', 63),
('Hanwha Group', 63),
('Hyundai Heavy Industries', 63),
('Hyundai Motor Group', 63),
('Korea Aerospace Industries (KAI)', 63),
('LIG Nex1', 63),
('SNT Dynamics', 63),
('SNT Motiv', 63),
('Astilleros Gondán', 64),
('Dikar S. Coop.', 64),
('Expal', 64),
('Indra Sistemas', 64),
('Instalaza', 64),
('Navantia', 64),
('Rodman Group', 64),
('SENER', 64),
('Armas Ugartechea', 64),
('Colombo Dockyard', 65),
('Military Industry Corporation (MIC Sudan)', 66),
('BAE Systems AB', 67),
('Bromma Air Maintenance AB', 67),
('Saab AB', 67),
('Swede Ship Marine AB', 67),
('B&T', 68),
('Pilatus Aircraft', 68),
('RUAG Holding Ltd', 68),
('Swiss Arms (SIG Sauer)', 68),
('Aerospace Industrial Development Corporation', 69),
('CSBC Corporation', 69),
('DronesVision', 69),
('Jong Shyn Shipbuilding Company', 69),
('Lungteh Shipbuilding', 69),
('National Chung-Shan Institute of Science and Technology', 69),
('Thunder Tiger', 69),
('Bangkok Dock', 70),
('Chaiseri', 70),
('Thai Aviation Industry', 70),
('Ares Shipyard', 71),
('ASFAT Inc.', 71),
('ASELSAN', 71),
('Baykar', 71),
('BMC', 71),
('GİRSAN', 71),
('HAVELSAN', 71),
('Koç Holding', 71),
('Mechanical and Chemical Industry Corporation (MKEK)', 71),
('Nurol Holding (FNSS Defence Systems)', 71),
('Özyurt Arms', 71),
('ROKETSAN', 71),
('Sarsılmaz Arms', 71),
('TİSAŞ', 71),
('Turkish Aerospace Industries', 71),
('Kuznya na Rybalskomu', 72),
('LATEK OOO', 72),
('NPO Practika', 72),
('RPC Fort', 72),
('Ukroboronprom', 72),
('XADO Chemical Group (Snipex)', 72),
('PA Pivdenmash', 72),
('Zbroyar Ltd.', 72),
('Motor Sich', 72),
('Antonov', 72),
('Yuzhmash', 72),
('EDGE Group', 73),
('STREIT Group', 73),
('Accuracy International', 74),
('Babcock International', 74),
('BAE Systems', 74),
('Britten-Norman', 74),
('Chemring Group', 74),
('Eley Brothers', 74),
('Ferguson Marine', 74),
('Griffon Hoverwork', 74),
('GKN Sankey', 74),
('James Fisher & Sons', 74),
('James Purdey and Sons', 74),
('Marshall Aerospace and Defence Group', 74),
('Supacat', 74),
('W. W. Greener', 74),
('Webley & Scott', 74),
('Westley Richards', 74),
('AeroVironment', 75),
('American Derringer', 75),
('AM General', 75),
('ArmaLite', 75),
('Axon', 75),
('BAE Systems Inc.', 75),
('Barrett Firearms Manufacturing', 75),
('Black Hills Ammunition', 75),
('Boeing Defense Space & Security', 75),
('Bollinger Shipyards', 75),
('Bond Arms', 75),
('Brunswick Boat Group', 75),
('Bushmaster Firearms International', 75),
('Calico Light Weapons Systems', 75),
('Charter Arms', 75),
('CheyTac', 75),
('Colt''s Manufacturing Company', 75),
('Combined Systems Inc.', 75),
('Cooper Firearms', 75),
('Day & Zimmermann', 75),
('Daniel Defense', 75),
('Dead Air Silencers', 75),
('Derecktor Shipyards', 75),
('Desert Tech', 75),
('Freedom Arms', 75),
('General Atomics', 75),
('General Dynamics', 75),
('Gladding-Hearn Shipbuilding', 75),
('GM Defense', 75),
('Metal Shark Boats', 75),
('Harris Gunworks', 75),
('Henry Repeating Arms', 75),
('Hi-Point Firearms', 75),
('Hodgdon Yachts', 75),
('Honeywell', 75),
('Hornady Manufacturing Company', 75),
('Huntington Ingalls Industries', 75),
('International Motors', 75),
('Ithaca Gun Company', 75),
('Kahr Arms', 75),
('Kaman Aerospace', 75),
('Kel-Tec', 75),
('Kimber Manufacturing', 75),
('Knight''s Armament Company', 75),
('KRISS USA', 75),
('L3Harris Technologies', 75),
('Lehigh Defense', 75),
('Les Baer', 75),
('Lewis Machine & Tool Company', 75),
('Lockheed Martin', 75),
('LWRC International', 75),
('MD Helicopters', 75),
('North American Arms', 75),
('Northrop Grumman', 75),
('Nosler', 75),
('Noveske Rifleworks', 75),
('OF Mossberg & Sons', 75),
('Olin Corporation', 75),
('Oshkosh Corporation', 75),
('Palmetto State Armory', 75),
('Patriot Ordnance Factory', 75),
('Polaris Industries', 75),
('Rock River Arms', 75),
('RTX Corporation (Raytheon)', 75),
('Safariland', 75),
('SAFE Boats International', 75),
('Savage Arms', 75),
('Science Applications International Corporation', 75),
('Serbu Firearms', 75),
('Sierra Bullets', 75);